disabled_rules:
  - large_tuple
  - nesting
  - void_function_in_ternary

opt_in_rules:
  - discouraged_optional_collection

trailing_whitespace:
    ignores_empty_lines: true

line_length:
    warning: 180 #要想一下這個數字
    ignores_interpolated_strings: true
    
identifier_name:
    max_length:
        warning: 50 #讀到這個規則的時候要再看一下
    
statement_position:
    statement_mode: uncuddled_else
    
function_body_length:
    warning: 200 #要想一下這個數字
    
type_body_length:
    warning: 600 # test case 的檔案很長，看要不要拆開
    
file_length:
    warning: 700 # test case 的檔案很長，看要不要拆開
    
