# custom rules
custom_rules:
    sf_safe_symbol:
        name: "Safe SFSymbol"
        message: "Use `SFSafeSymbols` via `systemSymbol` parameters for type safety."
        regex: "(Image\\(systemName:)|(NSImage\\(symbolName:)|(Label[^,]+?,\\s*systemImage:)|(UIApplicationShortcutIcon\\(systemImageName:)"
        severity: warning

# default rules
disabled_rules:
    - large_tuple
    - nesting
    - void_function_in_ternary
    
function_body_length:
    error: 200

identifier_name:
    max_length:
        warning: 50
        
line_length:
    warning: 164
    ignores_interpolated_strings: true
    
redundant_void_return:
    include_closures: false
    
statement_position:
    statement_mode: uncuddled_else
    
trailing_whitespace:
    ignores_empty_lines: true
    
type_body_length:
    warning: 600 # test case 的檔案很長，看要不要拆開
    
# opt-in rules
opt_in_rules:
    - anonymous_argument_in_multiline_closure
    - array_init
    - attributes
    - balanced_xctest_lifecycle
    - closure_body_length
    - closure_end_indentation
    - closure_spacing
    - collection_alignment
    - discouraged_optional_collection

attributes:
    always_on_same_line:
        - "@IBAction"
        - "@IBOutlet"
        - "@IBSegueAction"
        - "@escaping"
        - "@autoclosure"
        - "@Sendable"
        - "@testable"
    always_on_line_above:
        - "@discardableResult"
        - "@MainActor"
