# custom rules
custom_rules:
    sf_safe_symbol:
        name: "Safe SFSymbol"
        message: "Use `SFSafeSymbols` via `systemSymbol` parameters for type safety."
        regex: "(Image\\(systemName:)|(NSImage\\(symbolName:)|(Label[^,]+?,\\s*systemImage:)|(UIApplicationShortcutIcon\\(systemImageName:)"
        severity: warning

# default rules
disabled_rules:
    - large_tuple
    - nesting
    - void_function_in_ternary
    
function_body_length:
    error: 200

identifier_name:
    max_length:
        warning: 50
        
line_length:
    warning: 164
    ignores_interpolated_strings: true
    
redundant_void_return:
    include_closures: false
    
statement_position:
    statement_mode: uncuddled_else
    
trailing_whitespace:
    ignores_empty_lines: true
    
type_body_length:
    warning: 600 # test case 的檔案很長，看要不要拆開
    
# opt-in rules
opt_in_rules:
    - anonymous_argument_in_multiline_closure
    - array_init
    - attributes
    - balanced_xctest_lifecycle
    - closure_body_length
    - closure_end_indentation
    - closure_spacing
    - collection_alignment
    - comma_inheritance
    - contains_over_filter_count
    - contains_over_filter_is_empty
    - contains_over_first_not_nil
    - contains_over_range_nil_comparison
    - convenience_type
    - direct_return
    - discarded_notification_center_observer
    - discouraged_assert
    - discouraged_none_name
    - discouraged_object_literal
    - empty_collection_literal
    - empty_count
    - empty_string
    - empty_xctest_method
    - expiring_todo
    - explicit_init
    - explicit_type_interface
    - extension_access_modifier
    - fallthrough
    - fatal_error_message
    - file_types_order
    - final_test_case
    - first_where
    - flatmap_over_map_reduce
    - force_unwrapping
    - function_default_parameter_at_end
    - identical_operands
    - implicit_return
    - indentation_width
    - inert_defer
    - joined_default_parameter
    - last_where
    - legacy_multiple
    - legacy_objc_type
    - literal_expression_end_indentation
    - local_doc_comment
    - lower_acl_than_parent
    - modifier_order
    - multiline_arguments
    - multiline_function_chains
    - multiline_literal_brackets
    - multiline_parameters
    - multiline_parameters_brackets
    - no_magic_numbers
    - non_overridable_class_declaration
    - nslocalizedstring_key
    - nslocalizedstring_require_bundle
    - one_declaration_per_file
    - operator_usage_whitespace
    - optional_enum_case_matching
    - pattern_matching_keywords
    - period_spacing
    - prefer_self_in_static_references
    - prefer_self_type_over_type_of_self
    - prefer_zero_over_explicit_init
    - private_action
    - private_outlet
    - private_subject
    - reduce_into
    - redundant_nil_coalescing
    - redundant_self_in_closure
    - return_value_from_void_function
    - self_binding
    - shorthand_optional_binding
    - single_test_class
    - sorted_first_last
    - static_operator
    - strong_iboutlet
    - superfluous_else
    - test_case_accessibility
    - toggle_bool
    - trailing_closure
    - type_contents_order # 可以調整參數
    - unavailable_function
    - unhandled_throwing_task
    - unneeded_parentheses_in_closure_argument
    - untyped_error_in_catch
    - unused_capture_list
    - vertical_parameter_alignment_on_call
    - vertical_whitespace_closing_braces
    - vertical_whitespace_opening_braces
    - xct_specific_matcher

attributes:
    always_on_same_line:
        - "@IBAction"
        - "@IBOutlet"
        - "@IBSegueAction"
        - "@escaping"
        - "@autoclosure"
        - "@Sendable"
        - "@testable"
    always_on_line_above:
        - "@discardableResult"
        - "@MainActor"

expiring_todo:
    date_format: "yyyy/MM/dd"
    
