# custom rules
custom_rules:
  sf_safe_symbol:
    name: "Safe SFSymbol"
    message: "Use `SFSafeSymbols` via `systemSymbol` parameters for type safety."
    regex: "(Image\\(systemName:)|(NSImage\\(symbolName:)|(Label[^,]+?,\\s*systemImage:)|(UIApplicationShortcutIcon\\(systemImageName:)"
    severity: warning

# default rules
disabled_rules:
  - large_tuple
  - nesting
  - void_function_in_ternary

identifier_name:
    max_length:
        warning: 50
        
line_length:
    warning: 164
    ignores_interpolated_strings: true
    
# opt-in rules
opt_in_rules:
  - discouraged_optional_collection

    
###########
statement_position:
    statement_mode: uncuddled_else
    
trailing_whitespace:
    ignores_empty_lines: true
    
type_body_length:
    warning: 600 # test case 的檔案很長，看要不要拆開
