disabled_rules:
  - large_tuple
  - nesting
  - void_function_in_ternary

identifier_name:
    max_length:
        warning: 50
        
opt_in_rules:
  - discouraged_optional_collection

line_length:
    warning: 164
    ignores_interpolated_strings: true
    
###########
statement_position:
    statement_mode: uncuddled_else
    
trailing_whitespace:
    ignores_empty_lines: true
    
type_body_length:
    warning: 600 # test case 的檔案很長，看要不要拆開
